/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.zo.domain.tables.records;


import cn.vertxup.zo.domain.tables.ZoRoom;
import cn.vertxup.zo.domain.tables.interfaces.IZoRoom;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ZoRoomRecord extends UpdatableRecordImpl<ZoRoomRecord> implements VertxPojo, Record17<String, String, String, String, String, String, String, String, String, String, Boolean, String, String, String, LocalDateTime, String, LocalDateTime>, IZoRoom {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.PK_ID</code>. uniqueId,PK_ID
     */
    @Override
    public ZoRoomRecord setPkId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.PK_ID</code>. uniqueId,PK_ID
     */
    @Override
    public String getPkId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.T_ROOMATTRS</code>.
     * attrs,T_ROOMATTRS
     */
    @Override
    public ZoRoomRecord setTRoomattrs(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.T_ROOMATTRS</code>.
     * attrs,T_ROOMATTRS
     */
    @Override
    public String getTRoomattrs() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.S_CODE</code>. code,S_CODE
     */
    @Override
    public ZoRoomRecord setSCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.S_CODE</code>. code,S_CODE
     */
    @Override
    public String getSCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.S_ROOM_NUM</code>. number,S_ROOM_NUM
     */
    @Override
    public ZoRoomRecord setSRoomNum(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.S_ROOM_NUM</code>. number,S_ROOM_NUM
     */
    @Override
    public String getSRoomNum() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.J_CONFIG</code>. config,J_CONFIG
     */
    @Override
    public ZoRoomRecord setJConfig(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.J_CONFIG</code>. config,J_CONFIG
     */
    @Override
    public String getJConfig() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.J_FEATURES</code>.
     * features,J_FEATURES
     */
    @Override
    public ZoRoomRecord setJFeatures(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.J_FEATURES</code>.
     * features,J_FEATURES
     */
    @Override
    public String getJFeatures() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.R_FLOOR_ID</code>. floor,R_FLOOR_ID
     */
    @Override
    public ZoRoomRecord setRFloorId(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.R_FLOOR_ID</code>. floor,R_FLOOR_ID
     */
    @Override
    public String getRFloorId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.R_HOTEL_ID</code>.
     * hotelId,R_HOTEL_ID
     */
    @Override
    public ZoRoomRecord setRHotelId(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.R_HOTEL_ID</code>.
     * hotelId,R_HOTEL_ID
     */
    @Override
    public String getRHotelId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.R_ROOM_TYPE_ID</code>.
     * roomTypeId,R_ROOM_TYPE_ID
     */
    @Override
    public ZoRoomRecord setRRoomTypeId(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.R_ROOM_TYPE_ID</code>.
     * roomTypeId,R_ROOM_TYPE_ID
     */
    @Override
    public String getRRoomTypeId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.R_TENT_ID</code>. tent,R_TENT_ID
     */
    @Override
    public ZoRoomRecord setRTentId(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.R_TENT_ID</code>. tent,R_TENT_ID
     */
    @Override
    public String getRTentId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    @Override
    public ZoRoomRecord setIsActive(Boolean value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    @Override
    public Boolean getIsActive() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.Z_SIGMA</code>. sigma,Z_SIGMA
     */
    @Override
    public ZoRoomRecord setZSigma(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.Z_SIGMA</code>. sigma,Z_SIGMA
     */
    @Override
    public String getZSigma() {
        return (String) get(11);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.Z_LANGUAGE</code>.
     * language,Z_LANGUAGE
     */
    @Override
    public ZoRoomRecord setZLanguage(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.Z_LANGUAGE</code>.
     * language,Z_LANGUAGE
     */
    @Override
    public String getZLanguage() {
        return (String) get(12);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.Z_CREATE_BY</code>.
     * createBy,Z_CREATE_BY
     */
    @Override
    public ZoRoomRecord setZCreateBy(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.Z_CREATE_BY</code>.
     * createBy,Z_CREATE_BY
     */
    @Override
    public String getZCreateBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.Z_CREATE_TIME</code>.
     * createTime,Z_CREATE_TIME
     */
    @Override
    public ZoRoomRecord setZCreateTime(LocalDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.Z_CREATE_TIME</code>.
     * createTime,Z_CREATE_TIME
     */
    @Override
    public LocalDateTime getZCreateTime() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.Z_UPDATE_BY</code>.
     * updateBy,Z_UPDATE_BY
     */
    @Override
    public ZoRoomRecord setZUpdateBy(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.Z_UPDATE_BY</code>.
     * updateBy,Z_UPDATE_BY
     */
    @Override
    public String getZUpdateBy() {
        return (String) get(15);
    }

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.Z_UPDATE_TIME</code>.
     * updateTime,Z_UPDATE_TIME
     */
    @Override
    public ZoRoomRecord setZUpdateTime(LocalDateTime value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.Z_UPDATE_TIME</code>.
     * updateTime,Z_UPDATE_TIME
     */
    @Override
    public LocalDateTime getZUpdateTime() {
        return (LocalDateTime) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<String, String, String, String, String, String, String, String, String, String, Boolean, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<String, String, String, String, String, String, String, String, String, String, Boolean, String, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ZoRoom.ZO_ROOM.PK_ID;
    }

    @Override
    public Field<String> field2() {
        return ZoRoom.ZO_ROOM.T_ROOMATTRS;
    }

    @Override
    public Field<String> field3() {
        return ZoRoom.ZO_ROOM.S_CODE;
    }

    @Override
    public Field<String> field4() {
        return ZoRoom.ZO_ROOM.S_ROOM_NUM;
    }

    @Override
    public Field<String> field5() {
        return ZoRoom.ZO_ROOM.J_CONFIG;
    }

    @Override
    public Field<String> field6() {
        return ZoRoom.ZO_ROOM.J_FEATURES;
    }

    @Override
    public Field<String> field7() {
        return ZoRoom.ZO_ROOM.R_FLOOR_ID;
    }

    @Override
    public Field<String> field8() {
        return ZoRoom.ZO_ROOM.R_HOTEL_ID;
    }

    @Override
    public Field<String> field9() {
        return ZoRoom.ZO_ROOM.R_ROOM_TYPE_ID;
    }

    @Override
    public Field<String> field10() {
        return ZoRoom.ZO_ROOM.R_TENT_ID;
    }

    @Override
    public Field<Boolean> field11() {
        return ZoRoom.ZO_ROOM.IS_ACTIVE;
    }

    @Override
    public Field<String> field12() {
        return ZoRoom.ZO_ROOM.Z_SIGMA;
    }

    @Override
    public Field<String> field13() {
        return ZoRoom.ZO_ROOM.Z_LANGUAGE;
    }

    @Override
    public Field<String> field14() {
        return ZoRoom.ZO_ROOM.Z_CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return ZoRoom.ZO_ROOM.Z_CREATE_TIME;
    }

    @Override
    public Field<String> field16() {
        return ZoRoom.ZO_ROOM.Z_UPDATE_BY;
    }

    @Override
    public Field<LocalDateTime> field17() {
        return ZoRoom.ZO_ROOM.Z_UPDATE_TIME;
    }

    @Override
    public String component1() {
        return getPkId();
    }

    @Override
    public String component2() {
        return getTRoomattrs();
    }

    @Override
    public String component3() {
        return getSCode();
    }

    @Override
    public String component4() {
        return getSRoomNum();
    }

    @Override
    public String component5() {
        return getJConfig();
    }

    @Override
    public String component6() {
        return getJFeatures();
    }

    @Override
    public String component7() {
        return getRFloorId();
    }

    @Override
    public String component8() {
        return getRHotelId();
    }

    @Override
    public String component9() {
        return getRRoomTypeId();
    }

    @Override
    public String component10() {
        return getRTentId();
    }

    @Override
    public Boolean component11() {
        return getIsActive();
    }

    @Override
    public String component12() {
        return getZSigma();
    }

    @Override
    public String component13() {
        return getZLanguage();
    }

    @Override
    public String component14() {
        return getZCreateBy();
    }

    @Override
    public LocalDateTime component15() {
        return getZCreateTime();
    }

    @Override
    public String component16() {
        return getZUpdateBy();
    }

    @Override
    public LocalDateTime component17() {
        return getZUpdateTime();
    }

    @Override
    public String value1() {
        return getPkId();
    }

    @Override
    public String value2() {
        return getTRoomattrs();
    }

    @Override
    public String value3() {
        return getSCode();
    }

    @Override
    public String value4() {
        return getSRoomNum();
    }

    @Override
    public String value5() {
        return getJConfig();
    }

    @Override
    public String value6() {
        return getJFeatures();
    }

    @Override
    public String value7() {
        return getRFloorId();
    }

    @Override
    public String value8() {
        return getRHotelId();
    }

    @Override
    public String value9() {
        return getRRoomTypeId();
    }

    @Override
    public String value10() {
        return getRTentId();
    }

    @Override
    public Boolean value11() {
        return getIsActive();
    }

    @Override
    public String value12() {
        return getZSigma();
    }

    @Override
    public String value13() {
        return getZLanguage();
    }

    @Override
    public String value14() {
        return getZCreateBy();
    }

    @Override
    public LocalDateTime value15() {
        return getZCreateTime();
    }

    @Override
    public String value16() {
        return getZUpdateBy();
    }

    @Override
    public LocalDateTime value17() {
        return getZUpdateTime();
    }

    @Override
    public ZoRoomRecord value1(String value) {
        setPkId(value);
        return this;
    }

    @Override
    public ZoRoomRecord value2(String value) {
        setTRoomattrs(value);
        return this;
    }

    @Override
    public ZoRoomRecord value3(String value) {
        setSCode(value);
        return this;
    }

    @Override
    public ZoRoomRecord value4(String value) {
        setSRoomNum(value);
        return this;
    }

    @Override
    public ZoRoomRecord value5(String value) {
        setJConfig(value);
        return this;
    }

    @Override
    public ZoRoomRecord value6(String value) {
        setJFeatures(value);
        return this;
    }

    @Override
    public ZoRoomRecord value7(String value) {
        setRFloorId(value);
        return this;
    }

    @Override
    public ZoRoomRecord value8(String value) {
        setRHotelId(value);
        return this;
    }

    @Override
    public ZoRoomRecord value9(String value) {
        setRRoomTypeId(value);
        return this;
    }

    @Override
    public ZoRoomRecord value10(String value) {
        setRTentId(value);
        return this;
    }

    @Override
    public ZoRoomRecord value11(Boolean value) {
        setIsActive(value);
        return this;
    }

    @Override
    public ZoRoomRecord value12(String value) {
        setZSigma(value);
        return this;
    }

    @Override
    public ZoRoomRecord value13(String value) {
        setZLanguage(value);
        return this;
    }

    @Override
    public ZoRoomRecord value14(String value) {
        setZCreateBy(value);
        return this;
    }

    @Override
    public ZoRoomRecord value15(LocalDateTime value) {
        setZCreateTime(value);
        return this;
    }

    @Override
    public ZoRoomRecord value16(String value) {
        setZUpdateBy(value);
        return this;
    }

    @Override
    public ZoRoomRecord value17(LocalDateTime value) {
        setZUpdateTime(value);
        return this;
    }

    @Override
    public ZoRoomRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Boolean value11, String value12, String value13, String value14, LocalDateTime value15, String value16, LocalDateTime value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IZoRoom from) {
        setPkId(from.getPkId());
        setTRoomattrs(from.getTRoomattrs());
        setSCode(from.getSCode());
        setSRoomNum(from.getSRoomNum());
        setJConfig(from.getJConfig());
        setJFeatures(from.getJFeatures());
        setRFloorId(from.getRFloorId());
        setRHotelId(from.getRHotelId());
        setRRoomTypeId(from.getRRoomTypeId());
        setRTentId(from.getRTentId());
        setIsActive(from.getIsActive());
        setZSigma(from.getZSigma());
        setZLanguage(from.getZLanguage());
        setZCreateBy(from.getZCreateBy());
        setZCreateTime(from.getZCreateTime());
        setZUpdateBy(from.getZUpdateBy());
        setZUpdateTime(from.getZUpdateTime());
    }

    @Override
    public <E extends IZoRoom> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ZoRoomRecord
     */
    public ZoRoomRecord() {
        super(ZoRoom.ZO_ROOM);
    }

    /**
     * Create a detached, initialised ZoRoomRecord
     */
    public ZoRoomRecord(String pkId, String tRoomattrs, String sCode, String sRoomNum, String jConfig, String jFeatures, String rFloorId, String rHotelId, String rRoomTypeId, String rTentId, Boolean isActive, String zSigma, String zLanguage, String zCreateBy, LocalDateTime zCreateTime, String zUpdateBy, LocalDateTime zUpdateTime) {
        super(ZoRoom.ZO_ROOM);

        setPkId(pkId);
        setTRoomattrs(tRoomattrs);
        setSCode(sCode);
        setSRoomNum(sRoomNum);
        setJConfig(jConfig);
        setJFeatures(jFeatures);
        setRFloorId(rFloorId);
        setRHotelId(rHotelId);
        setRRoomTypeId(rRoomTypeId);
        setRTentId(rTentId);
        setIsActive(isActive);
        setZSigma(zSigma);
        setZLanguage(zLanguage);
        setZCreateBy(zCreateBy);
        setZCreateTime(zCreateTime);
        setZUpdateBy(zUpdateBy);
        setZUpdateTime(zUpdateTime);
    }

    /**
     * Create a detached, initialised ZoRoomRecord
     */
    public ZoRoomRecord(cn.vertxup.zo.domain.tables.pojos.ZoRoom value) {
        super(ZoRoom.ZO_ROOM);

        if (value != null) {
            setPkId(value.getPkId());
            setTRoomattrs(value.getTRoomattrs());
            setSCode(value.getSCode());
            setSRoomNum(value.getSRoomNum());
            setJConfig(value.getJConfig());
            setJFeatures(value.getJFeatures());
            setRFloorId(value.getRFloorId());
            setRHotelId(value.getRHotelId());
            setRRoomTypeId(value.getRRoomTypeId());
            setRTentId(value.getRTentId());
            setIsActive(value.getIsActive());
            setZSigma(value.getZSigma());
            setZLanguage(value.getZLanguage());
            setZCreateBy(value.getZCreateBy());
            setZCreateTime(value.getZCreateTime());
            setZUpdateBy(value.getZUpdateBy());
            setZUpdateTime(value.getZUpdateTime());
        }
    }

        public ZoRoomRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
