/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.zo.domain.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IZoRoom extends VertxPojo, Serializable {

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.PK_ID</code>. uniqueId,PK_ID
     */
    public IZoRoom setPkId(String value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.PK_ID</code>. uniqueId,PK_ID
     */
    public String getPkId();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.T_ROOMATTRS</code>.
     * attrs,T_ROOMATTRS
     */
    public IZoRoom setTRoomattrs(String value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.T_ROOMATTRS</code>.
     * attrs,T_ROOMATTRS
     */
    public String getTRoomattrs();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.S_CODE</code>. code,S_CODE
     */
    public IZoRoom setSCode(String value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.S_CODE</code>. code,S_CODE
     */
    public String getSCode();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.S_ROOM_NUM</code>. number,S_ROOM_NUM
     */
    public IZoRoom setSRoomNum(String value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.S_ROOM_NUM</code>. number,S_ROOM_NUM
     */
    public String getSRoomNum();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.J_CONFIG</code>. config,J_CONFIG
     */
    public IZoRoom setJConfig(String value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.J_CONFIG</code>. config,J_CONFIG
     */
    public String getJConfig();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.J_FEATURES</code>.
     * features,J_FEATURES
     */
    public IZoRoom setJFeatures(String value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.J_FEATURES</code>.
     * features,J_FEATURES
     */
    public String getJFeatures();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.R_FLOOR_ID</code>. floor,R_FLOOR_ID
     */
    public IZoRoom setRFloorId(String value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.R_FLOOR_ID</code>. floor,R_FLOOR_ID
     */
    public String getRFloorId();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.R_HOTEL_ID</code>.
     * hotelId,R_HOTEL_ID
     */
    public IZoRoom setRHotelId(String value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.R_HOTEL_ID</code>.
     * hotelId,R_HOTEL_ID
     */
    public String getRHotelId();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.R_ROOM_TYPE_ID</code>.
     * roomTypeId,R_ROOM_TYPE_ID
     */
    public IZoRoom setRRoomTypeId(String value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.R_ROOM_TYPE_ID</code>.
     * roomTypeId,R_ROOM_TYPE_ID
     */
    public String getRRoomTypeId();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.R_TENT_ID</code>. tent,R_TENT_ID
     */
    public IZoRoom setRTentId(String value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.R_TENT_ID</code>. tent,R_TENT_ID
     */
    public String getRTentId();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    public IZoRoom setIsActive(Boolean value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    public Boolean getIsActive();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.Z_SIGMA</code>. sigma,Z_SIGMA
     */
    public IZoRoom setZSigma(String value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.Z_SIGMA</code>. sigma,Z_SIGMA
     */
    public String getZSigma();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.Z_LANGUAGE</code>.
     * language,Z_LANGUAGE
     */
    public IZoRoom setZLanguage(String value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.Z_LANGUAGE</code>.
     * language,Z_LANGUAGE
     */
    public String getZLanguage();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.Z_CREATE_BY</code>.
     * createBy,Z_CREATE_BY
     */
    public IZoRoom setZCreateBy(String value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.Z_CREATE_BY</code>.
     * createBy,Z_CREATE_BY
     */
    public String getZCreateBy();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.Z_CREATE_TIME</code>.
     * createTime,Z_CREATE_TIME
     */
    public IZoRoom setZCreateTime(LocalDateTime value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.Z_CREATE_TIME</code>.
     * createTime,Z_CREATE_TIME
     */
    public LocalDateTime getZCreateTime();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.Z_UPDATE_BY</code>.
     * updateBy,Z_UPDATE_BY
     */
    public IZoRoom setZUpdateBy(String value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.Z_UPDATE_BY</code>.
     * updateBy,Z_UPDATE_BY
     */
    public String getZUpdateBy();

    /**
     * Setter for <code>DB_SCAFFOLD.ZO_ROOM.Z_UPDATE_TIME</code>.
     * updateTime,Z_UPDATE_TIME
     */
    public IZoRoom setZUpdateTime(LocalDateTime value);

    /**
     * Getter for <code>DB_SCAFFOLD.ZO_ROOM.Z_UPDATE_TIME</code>.
     * updateTime,Z_UPDATE_TIME
     */
    public LocalDateTime getZUpdateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IZoRoom
     */
    public void from(IZoRoom from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IZoRoom
     */
    public <E extends IZoRoom> E into(E into);

        @Override
        public default IZoRoom fromJson(io.vertx.core.json.JsonObject json) {
                setOrThrow(this::setPkId,json::getString,"PK_ID","java.lang.String");
                setOrThrow(this::setTRoomattrs,json::getString,"T_ROOMATTRS","java.lang.String");
                setOrThrow(this::setSCode,json::getString,"S_CODE","java.lang.String");
                setOrThrow(this::setSRoomNum,json::getString,"S_ROOM_NUM","java.lang.String");
                setOrThrow(this::setJConfig,json::getString,"J_CONFIG","java.lang.String");
                setOrThrow(this::setJFeatures,json::getString,"J_FEATURES","java.lang.String");
                setOrThrow(this::setRFloorId,json::getString,"R_FLOOR_ID","java.lang.String");
                setOrThrow(this::setRHotelId,json::getString,"R_HOTEL_ID","java.lang.String");
                setOrThrow(this::setRRoomTypeId,json::getString,"R_ROOM_TYPE_ID","java.lang.String");
                setOrThrow(this::setRTentId,json::getString,"R_TENT_ID","java.lang.String");
                setOrThrow(this::setIsActive,json::getBoolean,"IS_ACTIVE","java.lang.Boolean");
                setOrThrow(this::setZSigma,json::getString,"Z_SIGMA","java.lang.String");
                setOrThrow(this::setZLanguage,json::getString,"Z_LANGUAGE","java.lang.String");
                setOrThrow(this::setZCreateBy,json::getString,"Z_CREATE_BY","java.lang.String");
                setOrThrow(this::setZCreateTime,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"Z_CREATE_TIME","java.time.LocalDateTime");
                setOrThrow(this::setZUpdateBy,json::getString,"Z_UPDATE_BY","java.lang.String");
                setOrThrow(this::setZUpdateTime,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"Z_UPDATE_TIME","java.time.LocalDateTime");
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                json.put("PK_ID",getPkId());
                json.put("T_ROOMATTRS",getTRoomattrs());
                json.put("S_CODE",getSCode());
                json.put("S_ROOM_NUM",getSRoomNum());
                json.put("J_CONFIG",getJConfig());
                json.put("J_FEATURES",getJFeatures());
                json.put("R_FLOOR_ID",getRFloorId());
                json.put("R_HOTEL_ID",getRHotelId());
                json.put("R_ROOM_TYPE_ID",getRRoomTypeId());
                json.put("R_TENT_ID",getRTentId());
                json.put("IS_ACTIVE",getIsActive());
                json.put("Z_SIGMA",getZSigma());
                json.put("Z_LANGUAGE",getZLanguage());
                json.put("Z_CREATE_BY",getZCreateBy());
                json.put("Z_CREATE_TIME",getZCreateTime()==null?null:getZCreateTime().toString());
                json.put("Z_UPDATE_BY",getZUpdateBy());
                json.put("Z_UPDATE_TIME",getZUpdateTime()==null?null:getZUpdateTime().toString());
                return json;
        }

}
