/*
 * This file is generated by jOOQ.
 */
package cn.commerce.domain;


import cn.commerce.domain.tables.ZoCard;
import cn.commerce.domain.tables.ZoMember;

import java.util.Arrays;
import java.util.List;

import io.vertx.tp.ke.refine.Ke;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Db extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DB_SCAFFOLD</code>
     */
    public static final Db DB_SCAFFOLD = new Db();

    /**
     * The table <code>DB_SCAFFOLD.ZO_CARD</code>.
     */
    public final ZoCard ZO_CARD = ZoCard.ZO_CARD;

    /**
     * The table <code>DB_SCAFFOLD.ZO_MEMBER</code>.
     */
    public final ZoMember ZO_MEMBER = ZoMember.ZO_MEMBER;

    /**
     * No further instances allowed
     */
    private Db() {
        super(Ke.getDatabase(), null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ZoCard.ZO_CARD,
            ZoMember.ZO_MEMBER
        );
    }
}
