/*
 * This file is generated by jOOQ.
 */
package cn.commerce.domain;


import cn.commerce.domain.tables.ZoCard;
import cn.commerce.domain.tables.ZoMember;
import cn.commerce.domain.tables.records.ZoCardRecord;
import cn.commerce.domain.tables.records.ZoMemberRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * DB_SCAFFOLD.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ZoCardRecord> KEY_ZO_CARD_PRIMARY = Internal.createUniqueKey(ZoCard.ZO_CARD, DSL.name("KEY_ZO_CARD_PRIMARY"), new TableField[] { ZoCard.ZO_CARD.PK_ID }, true);
    public static final UniqueKey<ZoCardRecord> KEY_ZO_CARD_UK_ZO_CARD_S_CODE_Z_SIGMA = Internal.createUniqueKey(ZoCard.ZO_CARD, DSL.name("KEY_ZO_CARD_UK_ZO_CARD_S_CODE_Z_SIGMA"), new TableField[] { ZoCard.ZO_CARD.S_CODE, ZoCard.ZO_CARD.Z_SIGMA }, true);
    public static final UniqueKey<ZoCardRecord> KEY_ZO_CARD_UK_ZO_CARD_S_NUMBER_Z_SIGMA = Internal.createUniqueKey(ZoCard.ZO_CARD, DSL.name("KEY_ZO_CARD_UK_ZO_CARD_S_NUMBER_Z_SIGMA"), new TableField[] { ZoCard.ZO_CARD.S_NUMBER, ZoCard.ZO_CARD.Z_SIGMA }, true);
    public static final UniqueKey<ZoMemberRecord> KEY_ZO_MEMBER_PRIMARY = Internal.createUniqueKey(ZoMember.ZO_MEMBER, DSL.name("KEY_ZO_MEMBER_PRIMARY"), new TableField[] { ZoMember.ZO_MEMBER.PK_ID }, true);
    public static final UniqueKey<ZoMemberRecord> KEY_ZO_MEMBER_UK_ZO_MEMBER_S_CODE_Z_SIGMA = Internal.createUniqueKey(ZoMember.ZO_MEMBER, DSL.name("KEY_ZO_MEMBER_UK_ZO_MEMBER_S_CODE_Z_SIGMA"), new TableField[] { ZoMember.ZO_MEMBER.S_CODE, ZoMember.ZO_MEMBER.Z_SIGMA }, true);
    public static final UniqueKey<ZoMemberRecord> KEY_ZO_MEMBER_UK_ZO_MEMBER_S_MOBILE_Z_SIGMA = Internal.createUniqueKey(ZoMember.ZO_MEMBER, DSL.name("KEY_ZO_MEMBER_UK_ZO_MEMBER_S_MOBILE_Z_SIGMA"), new TableField[] { ZoMember.ZO_MEMBER.S_MOBILE, ZoMember.ZO_MEMBER.Z_SIGMA }, true);
}
