/*
 * This file is generated by jOOQ.
 */
package cn.commerce.domain;


import cn.commerce.domain.tables.ZoCard;
import cn.commerce.domain.tables.ZoMember;


/**
 * Convenience access to all tables in DB_SCAFFOLD.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DB_SCAFFOLD.ZO_CARD</code>.
     */
    public static final ZoCard ZO_CARD = ZoCard.ZO_CARD;

    /**
     * The table <code>DB_SCAFFOLD.ZO_MEMBER</code>.
     */
    public static final ZoMember ZO_MEMBER = ZoMember.ZO_MEMBER;
}
