SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
-- 删除原来的数据库
DROP DATABASE IF EXISTS DB_QIANLI;
CREATE DATABASE IF NOT EXISTS DB_QIANLI DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- 删除原来的数据库
DROP DATABASE IF EXISTS DB_QIANLI_WF;
CREATE DATABASE IF NOT EXISTS DB_QIANLI_WF DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_bin;