SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
-- 删除原来的数据库
DROP DATABASE IF EXISTS DB_SCAFFOLD;
CREATE DATABASE IF NOT EXISTS DB_SCAFFOLD DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_bin;
DROP DATABASE IF EXISTS DB_SCAFFOLD_WF;
CREATE DATABASE IF NOT EXISTS DB_SCAFFOLD_WF DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_bin;