/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.zo.domain;


import cn.vertxup.zo.domain.tables.ZoRoom;
import cn.vertxup.zo.domain.tables.records.ZoRoomRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * DB_SCAFFOLD.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ZoRoomRecord> KEY_ZO_ROOM_PRIMARY = Internal.createUniqueKey(ZoRoom.ZO_ROOM, DSL.name("KEY_ZO_ROOM_PRIMARY"), new TableField[] { ZoRoom.ZO_ROOM.PK_ID }, true);
    public static final UniqueKey<ZoRoomRecord> KEY_ZO_ROOM_UK_ZO_ROOM_S_CODE_Z_SIGMA = Internal.createUniqueKey(ZoRoom.ZO_ROOM, DSL.name("KEY_ZO_ROOM_UK_ZO_ROOM_S_CODE_Z_SIGMA"), new TableField[] { ZoRoom.ZO_ROOM.S_CODE, ZoRoom.ZO_ROOM.Z_SIGMA }, true);
}
