/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.zo.domain;


import cn.vertxup.zo.domain.tables.ZoRoom;


/**
 * Convenience access to all tables in DB_SCAFFOLD.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DB_SCAFFOLD.ZO_ROOM</code>.
     */
    public static final ZoRoom ZO_ROOM = ZoRoom.ZO_ROOM;
}
