databaseChangeLog:
  # liquibase.exception.DatabaseException: The table does not comply with the requirements by an external plugin
  - preConditions:
      customPrecondition:
        className: io.vertx.up.plugin.database.LiquibaseMySQL8Pre
  # 界面表
  - include:
      file: plugin/ui/db.yml
      relativeToChangelogFile: false
  # 安全表
  - include:
      file: plugin/rbac/db.yml
      relativeToChangelogFile: false
  # 系统表
  - include:
      file: plugin/ambient/db.yml
      relativeToChangelogFile: false
  # Erp企业信息表
  - include:
      file: plugin/erp/db.yml
      relativeToChangelogFile: false
  # 地址表
  - include:
      file: plugin/lbs/db.yml
      relativeToChangelogFile: false
  # 财务系统
  - include:
      file: plugin/fm/db.yml
      relativeToChangelogFile: false
  # 进销存
  - include:
      file: plugin/psi/db.yml
      relativeToChangelogFile: false
  # 建模表
  - include:
      file: plugin/atom/db.yml
      relativeToChangelogFile: false
  # 图引擎
  - include:
      file: plugin/graphic/db.yml
      relativeToChangelogFile: false
  # Jet
  - include:
      file: plugin/jet/db.yml
      relativeToChangelogFile: false
  # Workflow
  - include:
      file: plugin/wf/db.yml
      relativeToChangelogFile: false
  # Is
  - include:
      file: plugin/is/db.yml
      relativeToChangelogFile: false
  # Bettery
  - include:
      file: plugin/battery/db.yml
      relativeToChangelogFile: false
  # Tpl
  - include:
      file: plugin/tpl/db.yml
      relativeToChangelogFile: false
  # 示例系统
  - include:
      file: plugin/sql/commerce.yml
      relativeToChangelogFile: false