databaseChangeLog:
  # liquibase.exception.DatabaseException: The table does not comply with the requirements by an external plugin
  - preConditions:
      customPrecondition:
        className: io.vertx.tp.plugin.database.LiquibaseMySQL8Pre
  # 界面表
  - include:
      file: plugin/sql/ui.yml
      relativeToChangelogFile: false
  # 安全表
  - include:
      file: plugin/sql/rbac.yml
      relativeToChangelogFile: false
  # 系统表
  - include:
      file: plugin/sql/ambient.yml
      relativeToChangelogFile: false
  # Erp企业信息表
  - include:
      file: plugin/sql/erp.yml
      relativeToChangelogFile: false
  - include:
      file: plugin/sql/erp-workflow.yml
      relativeToChangelogFile: false
  # 地址表
  - include:
      file: plugin/sql/lbs.yml
      relativeToChangelogFile: false
  # 财务系统
  - include:
      file: plugin/sql/fm.yml
      relativeToChangelogFile: false
  # 进销存
  - include:
      file: plugin/sql/psi.yml
      relativeToChangelogFile: false
  # 建模表
  - include:
      file: plugin/sql/atom.yml
      relativeToChangelogFile: false
  # 图引擎
  - include:
      file: plugin/sql/graphic.yml
      relativeToChangelogFile: false
  # Jet
  - include:
      file: plugin/sql/jet.yml
      relativeToChangelogFile: false
  # Workflow
  - include:
      file: plugin/sql/wf.yml
      relativeToChangelogFile: false
  # Is
  - include:
      file: plugin/sql/is.yml
      relativeToChangelogFile: false
  # Bettery
  - include:
      file: plugin/sql/battery.yml
      relativeToChangelogFile: false
  # Tpl
  - include:
      file: plugin/sql/tpl.yml
      relativeToChangelogFile: false
  # 示例系统
  - include:
      file: plugin/sql/commerce.yml
      relativeToChangelogFile: false